// API CALL FOR ALL MOVIES WITH A SPECIFIC TITLE
export const REQUEST_MOVIES='REQUEST_MOVIES'
export const GET_MOVIES_SUCCESS='GET_MOVIES_SUCCESS'
export const GET_MOVIES_FAILURE='GET_MOVIES_FAILURE'
// API CALL FOR INFO ON A SINGLE MOVIE
export const REQUEST_MOVIE_INFO='REQUEST_MOVIE_INFO'
export const GET_MOVIE_INFO_SUCCESS='GET_MOVIE_INFO_SUCCESS'
export const GET_MOVIE_INFO_FAILURE='GET_MOVIE_INFO_FAILURE'
